.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/controllers/axis/AnalogAxis.cpp" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/controllers/axis/AnalogAxis.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <frc/GenericHID\&.h>\fP
.br
\fC#include <controllers/axis/AnalogAxis\&.h>\fP
.br
\fC#include <controllers/axis/LinearProfile\&.h>\fP
.br
\fC#include <controllers/axis/CubedProfile\&.h>\fP
.br
\fC#include <controllers/axis/DeadbandValue\&.h>\fP
.br
\fC#include <controllers/axis/FlippedAxis\&.h>\fP
.br
\fC#include <controllers/axis/NoDeadbandValue\&.h>\fP
.br
\fC#include <controllers/axis/ScaledDeadbandValue\&.h>\fP
.br
\fC#include <controllers/axis/SquaredProfile\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
