.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/gamepad/axis/AnalogAxis.h" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/gamepad/axis/AnalogAxis.h
.SH SYNOPSIS
.br
.PP
\fC#include <frc/GenericHID\&.h>\fP
.br
\fC#include <gamepad/IDragonGamePad\&.h>\fP
.br
\fC#include <gamepad/axis/IProfile\&.h>\fP
.br
\fC#include <gamepad/axis/IDeadband\&.h>\fP
.br
\fC#include <gamepad/axis/ScaledAxis\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnalogAxis\fP"
.br
.RI "Class: \fBAnalogAxis\fP Description: This class handles the analog inputs on a gamepad "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
