.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/controllers/button/ButtonDecorator.h" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/controllers/button/ButtonDecorator.h
.SH SYNOPSIS
.br
.PP
\fC#include <controllers/button/IButton\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBButtonDecorator\fP"
.br
.RI "Class: \fBButtonDecorator\fP Description: This is a decorator for modifying button behavior\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
