.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp Directory Reference" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcontrollers\fP"
.br
.ti -1c
.RI "directory \fBhw\fP"
.br
.ti -1c
.RI "directory \fBsubsys\fP"
.br
.ti -1c
.RI "directory \fButils\fP"
.br
.ti -1c
.RI "directory \fBxmlcontrol\fP"
.br
.ti -1c
.RI "directory \fBxmlhw\fP"
.br
.ti -1c
.RI "directory \fBxmlmechdata\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBRobot\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRobot\&.h\fP"
.br
.in -1c
