.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlhw/CameraDefn.cpp" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlhw/CameraDefn.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <xmlhw/CameraDefn\&.h>\fP
.br
\fC#include <pugixml/pugixml\&.hpp>\fP
.br
\fC#include <cameraserver/CameraServer\&.h>\fP
.br
\fC#include <cscore_cpp\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
