.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlhw/CANifierDefn.h" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlhw/CANifierDefn.h
.SH SYNOPSIS
.br
.PP
\fC#include <pugixml/pugixml\&.hpp>\fP
.br
\fC#include <ctre/Phoenix\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCANifierDefn\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
