.TH "CanifierFactory" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CanifierFactory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CanifierFactory\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ctre::phoenix::CANifier * \fBGetCanifier\fP (int canID)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCanifierFactory\fP * \fBGetInstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file CanifierFactory\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "ctre::phoenix::CANifier * CanifierFactory::GetCanifier (int canID)"

.PP
Definition at line 35 of file CanifierFactory\&.cpp\&.
.SS "\fBCanifierFactory\fP * CanifierFactory::GetInstance ()\fC [static]\fP"

.PP
Definition at line 11 of file CanifierFactory\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
