.TH "CANifierDefn" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CANifierDefn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CANifierDefn\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCANifierDefn\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~CANifierDefn\fP ()=default"
.br
.ti -1c
.RI "ctre::phoenix::CANifier * \fBParseXML\fP (pugi::xml_node canifierNode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file CANifierDefn\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CANifierDefn::CANifierDefn ()\fC [default]\fP"

.SS "virtual CANifierDefn::~CANifierDefn ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "ctre::phoenix::CANifier * CANifierDefn::ParseXML (pugi::xml_node canifierNode)"

.PP
Definition at line 20 of file CANifierDefn\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
