.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/controllers/button/DigitalButton.h" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/controllers/button/DigitalButton.h
.SH SYNOPSIS
.br
.PP
\fC#include <frc/GenericHID\&.h>\fP
.br
\fC#include <controllers/button/IButton\&.h>\fP
.br
\fC#include <controllers/IDragonGamePad\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDigitalButton\fP"
.br
.RI "Class: \fBDigitalButton\fP Description: This is the standard button on a gamepad\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
