.TH "DigitalInputDefn" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DigitalInputDefn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DigitalInputDefn\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDigitalInputDefn\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~DigitalInputDefn\fP ()=default"
.br
.ti -1c
.RI "\fBDragonDigitalInput\fP * \fBParseXML\fP (pugi::xml_node DigitalNode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file DigitalInputDefn\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DigitalInputDefn::DigitalInputDefn ()\fC [default]\fP"

.SS "virtual DigitalInputDefn::~DigitalInputDefn ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBDragonDigitalInput\fP * DigitalInputDefn::ParseXML (pugi::xml_node DigitalNode)"

.PP
Definition at line 68 of file DigitalInputDefn\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
