.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/controllers/DragonXBox.cpp" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/controllers/DragonXBox.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <controllers/DragonXBox\&.h>\fP
.br
\fC#include <controllers/axis/IDeadband\&.h>\fP
.br
\fC#include <controllers/axis/IProfile\&.h>\fP
.br
\fC#include <controllers/button/AnalogButton\&.h>\fP
.br
\fC#include <controllers/button/DigitalButton\&.h>\fP
.br
\fC#include <controllers/button/ButtonDecorator\&.h>\fP
.br
\fC#include <controllers/button/POVButton\&.h>\fP
.br
\fC#include <controllers/button/ToggleButton\&.h>\fP
.br
\fC#include <frc/GenericHID\&.h>\fP
.br
\fC#include <frc/XboxController\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
