.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/hw/DragonPigeon.h" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/hw/DragonPigeon.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <ctre/phoenix/Sensors/PigeonIMU\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDragonPigeon\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
