.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/hw/DragonPositionSensor.cpp" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/hw/DragonPositionSensor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <hw/DragonPositionSensor\&.h>\fP
.br
\fC#include <hw/IDragonAnglePositionSensor\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_USE_MATH_DEFINES\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _USE_MATH_DEFINES"

.PP
Definition at line 18 of file DragonPositionSensor\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
