.TH "DragonServoFactory" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DragonServoFactory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DragonServoFactory\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDragonServo\fP * \fBCreateDragonServo\fP (\fBDragonServo::SERVO_USAGE\fP deviceUsage, int deviceID, double minAngle, double maxAngle)"
.br
.ti -1c
.RI "\fBDragonServo\fP * \fBGetDragonServo\fP (\fBDragonServo::SERVO_USAGE\fP deviceUsage)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDragonServoFactory\fP * \fBGetInstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file DragonServoFactory\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDragonServo\fP * DragonServoFactory::CreateDragonServo (\fBDragonServo::SERVO_USAGE\fP deviceUsage, int deviceID, double minAngle, double maxAngle)"

.PP
Definition at line 70 of file DragonServoFactory\&.cpp\&.
.SS "\fBDragonServo\fP * DragonServoFactory::GetDragonServo (\fBDragonServo::SERVO_USAGE\fP deviceUsage)"

.PP
Definition at line 107 of file DragonServoFactory\&.cpp\&.
.SS "\fBDragonServoFactory\fP * DragonServoFactory::GetInstance ()\fC [static]\fP"

.PP
Definition at line 35 of file DragonServoFactory\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
