.TH "DragonPigeon" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DragonPigeon
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DragonPigeon\&.h>\fP
.PP
Inherits PigeonIMU\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBGetPitch\fP ()"
.br
.ti -1c
.RI "double \fBGetRoll\fP ()"
.br
.ti -1c
.RI "double \fBGetYaw\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDragonPigeon\fP * \fBGetPigeon\fP ()"
.br
.ti -1c
.RI "static void \fBCreatePigeon\fP (int id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file DragonPigeon\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void DragonPigeon::CreatePigeon (int id)\fC [static]\fP"

.PP
Definition at line 38 of file DragonPigeon\&.cpp\&.
.SS "\fBDragonPigeon\fP * DragonPigeon::GetPigeon ()\fC [static]\fP"

.PP
Definition at line 22 of file DragonPigeon\&.cpp\&.
.SS "double DragonPigeon::GetPitch ()"

.PP
Definition at line 43 of file DragonPigeon\&.cpp\&.
.SS "double DragonPigeon::GetRoll ()"

.PP
Definition at line 49 of file DragonPigeon\&.cpp\&.
.SS "double DragonPigeon::GetYaw ()"

.PP
Definition at line 54 of file DragonPigeon\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
