.TH "DragonVision" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DragonVision
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DragonVision\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDragonVision\fP ()"
.br
.ti -1c
.RI "\fB~DragonVision\fP ()"
.br
.ti -1c
.RI "cv::Mat \fBgetImage\fP ()"
.br
.ti -1c
.RI "int \fBgetWidth\fP (cv::Mat &image)"
.br
.ti -1c
.RI "int \fBgetHeight\fP (cv::Mat &image)"
.br
.ti -1c
.RI "void \fBshowCircle\fP (cv::Mat &image, int &width, int &height)"
.br
.ti -1c
.RI "void \fBshowCross\fP (cv::Mat &image, int &width, int &height)"
.br
.ti -1c
.RI "void \fBRotateVertically\fP (cv::Mat &image, cv::Mat &outputimage)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file DragonVision\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DragonVision::DragonVision ()"

.PP
Definition at line 11 of file DragonVision\&.cpp\&.
.SS "DragonVision::~DragonVision ()"

.PP
Definition at line 17 of file DragonVision\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int DragonVision::getHeight (cv::Mat & image)"

.PP
Definition at line 32 of file DragonVision\&.cpp\&.
.SS "cv::Mat DragonVision::getImage ()"

.PP
Definition at line 22 of file DragonVision\&.cpp\&.
.SS "int DragonVision::getWidth (cv::Mat & image)"

.PP
Definition at line 27 of file DragonVision\&.cpp\&.
.SS "void DragonVision::RotateVertically (cv::Mat & image, cv::Mat & outputimage)"

.PP
Definition at line 58 of file DragonVision\&.cpp\&.
.SS "void DragonVision::showCircle (cv::Mat & image, int & width, int & height)"

.PP
Definition at line 37 of file DragonVision\&.cpp\&.
.SS "void DragonVision::showCross (cv::Mat & image, int & width, int & height)"

.PP
Definition at line 46 of file DragonVision\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
