.TH "DragonUltrasonic" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DragonUltrasonic
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DragonUltrasonic\&.h>\fP
.PP
Inherits \fBIDragonUltrasonic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDragonUltrasonic\fP (\fBIDragonUltrasonic::ULTRASONIC_USAGE\fP usage, int analogInChannel)"
.br
.ti -1c
.RI "virtual \fB~DragonUltrasonic\fP ()"
.br
.ti -1c
.RI "double \fBGetDistance\fP () const override"
.br
.ti -1c
.RI "\fBIDragonUltrasonic::ULTRASONIC_USAGE\fP \fBGetUsage\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file DragonUltrasonic\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DragonUltrasonic::DragonUltrasonic (\fBIDragonUltrasonic::ULTRASONIC_USAGE\fP usage, int analogInChannel)"

.PP
Definition at line 15 of file DragonUltrasonic\&.cpp\&.
.SS "DragonUltrasonic::~DragonUltrasonic ()\fC [virtual]\fP"

.PP
Definition at line 23 of file DragonUltrasonic\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "double DragonUltrasonic::GetDistance () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIDragonUltrasonic\fP\&.
.PP
Definition at line 28 of file DragonUltrasonic\&.cpp\&.
.SS "\fBIDragonUltrasonic::ULTRASONIC_USAGE\fP DragonUltrasonic::GetUsage () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIDragonUltrasonic\fP\&.
.PP
Definition at line 32 of file DragonUltrasonic\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
