.TH "DragonPDP" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DragonPDP
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DragonPDP\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "PowerDistributionPanel * \fBCreatePDP\fP (int canID)"
.br
.ti -1c
.RI "frc::PowerDistributionPanel * \fBGetPDP\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDragonPDP\fP * \fBGetInstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file DragonPDP\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "PowerDistributionPanel * DragonPDP::CreatePDP (int canID)"

.PP
Definition at line 26 of file DragonPDP\&.cpp\&.
.SS "\fBDragonPDP\fP * DragonPDP::GetInstance ()\fC [static]\fP"

.PP
Definition at line 12 of file DragonPDP\&.cpp\&.
.SS "frc::PowerDistributionPanel* DragonPDP::GetPDP ()\fC [inline]\fP"

.PP
Definition at line 27 of file DragonPDP\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
