.TH "DragonUltrasonicPWM" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DragonUltrasonicPWM
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DragonUltrasonicPWM\&.h>\fP
.PP
Inherits \fBIDragonUltrasonic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDragonUltrasonicPWM\fP (\fBIDragonUltrasonic::ULTRASONIC_USAGE\fP usage, int digitalPinChannel)"
.br
.ti -1c
.RI "virtual \fB~DragonUltrasonicPWM\fP ()"
.br
.ti -1c
.RI "double \fBGetDistance\fP () const override"
.br
.ti -1c
.RI "\fBIDragonUltrasonic::ULTRASONIC_USAGE\fP \fBGetUsage\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file DragonUltrasonicPWM\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DragonUltrasonicPWM::DragonUltrasonicPWM (\fBIDragonUltrasonic::ULTRASONIC_USAGE\fP usage, int digitalPinChannel)"

.PP
Definition at line 11 of file DragonUltrasonicPWM\&.cpp\&.
.SS "DragonUltrasonicPWM::~DragonUltrasonicPWM ()\fC [virtual]\fP"

.PP
Definition at line 18 of file DragonUltrasonicPWM\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "double DragonUltrasonicPWM::GetDistance () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIDragonUltrasonic\fP\&.
.PP
Definition at line 22 of file DragonUltrasonicPWM\&.cpp\&.
.SS "\fBIDragonUltrasonic::ULTRASONIC_USAGE\fP DragonUltrasonicPWM::GetUsage () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIDragonUltrasonic\fP\&.
.PP
Definition at line 26 of file DragonUltrasonicPWM\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
