.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/gamepad/axis/FlippedAxis.cpp" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/gamepad/axis/FlippedAxis.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <gamepad/axis/FlippedAxis\&.h>\fP
.br
\fC#include <cmath>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
