.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/controllers/axis/FlippedAxis.h" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/controllers/axis/FlippedAxis.h
.SH SYNOPSIS
.br
.PP
\fC#include <controllers/axis/ScaledAxis\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFlippedAxis\fP"
.br
.RI "Class: \fBFlippedAxis\fP Description: This provides scaling for an axis that is reversed\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
