.TH "FlippedAxis" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlippedAxis \- Class: \fBFlippedAxis\fP Description: This provides scaling for an axis that is reversed\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FlippedAxis\&.h>\fP
.PP
Inherits \fBScaledAxis\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlippedAxis\fP ()"
.br
.ti -1c
.RI "\fB~FlippedAxis\fP ()=default"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class: \fBFlippedAxis\fP Description: This provides scaling for an axis that is reversed\&. 


.PP
Definition at line 37 of file FlippedAxis\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FlippedAxis::FlippedAxis ()"

.PP
Definition at line 29 of file FlippedAxis\&.cpp\&.
.SS "FlippedAxis::~FlippedAxis ()\fC [default]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
