.TH "HardwareIDValidation" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HardwareIDValidation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HardwareIDValidation\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBValidateCANID\fP (int canID, std::string methodID)"
.br
.in -1c
.SH "Detailed Description"
.PP 
======================================================================================================== 
.SH "HardwareIDValidation\&.h"
.PP
File Description: 
.SH "This will validate the various hardware IDs against the valid values\&."
.PP

.PP
Definition at line 38 of file HardwareIDValidation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool HardwareIDValidation::ValidateCANID (int canID, std::string methodID)\fC [static]\fP"
====================================================================================== Method: ValidateCANID Description: Check the CAN ID against the valid range\&. If it is invalid the logger utility will be called\&. Returns: bool true - valid 
.SH "false - invalid"
.PP
====================================================================================== Method: ValidateCANID Description: Check the CAN ID against the valid range\&. If it is invalid the logger utility will be called\&. Returns: bool true - valid 
.SH "false - invalid"
.PP

.PP
Definition at line 47 of file HardwareIDValidation\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
