.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/utils/HardwareIDValidation.cpp" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/utils/HardwareIDValidation.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <utils/HardwareIDValidation\&.h>\fP
.br
\fC#include <utils/Logger\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
