.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/gamepad/button/IButton.h" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/gamepad/button/IButton.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIButton\fP"
.br
.RI "Class: \fBIButton\fP Description: This interface is for treating gamepad inputs as digital inputs\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
