.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/subsys/Intake.h" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/subsys/Intake.h
.SH SYNOPSIS
.br
.PP
\fC#include <hw/IDragonMotorController\&.h>\fP
.br
\fC#include <subsys/IMechanism\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIntake\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
