.TH "IProfile" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IProfile \- Class: \fBIProfile\fP Description: This provides profile to be applied to input values\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IProfile\&.h>\fP
.PP
Inherited by \fBCubedProfile\fP, \fBLinearProfile\fP, and \fBSquaredProfile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual double \fBApplyProfile\fP (double inputVal) const =0"
.br
.RI "Method: ApplyProfile Description: Apply the profile "
.in -1c
.SH "Detailed Description"
.PP 
Class: \fBIProfile\fP Description: This provides profile to be applied to input values\&. 


.PP
Definition at line 36 of file IProfile\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual double IProfile::ApplyProfile (double inputVal) const\fC [pure virtual]\fP"

.PP
Method: ApplyProfile Description: Apply the profile 
.PP
Implemented in \fBLinearProfile\fP, \fBCubedProfile\fP, and \fBSquaredProfile\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
