.TH "LEDDefn" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LEDDefn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LEDDefn\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLEDDefn\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~LEDDefn\fP ()=default"
.br
.ti -1c
.RI "void \fBParseXML\fP (pugi::xml_node LEDNode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file LEDDefn\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LEDDefn::LEDDefn ()\fC [default]\fP"

.SS "virtual LEDDefn::~LEDDefn ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void LEDDefn::ParseXML (pugi::xml_node LEDNode)"

.PP
Definition at line 33 of file LEDDefn\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
