.TH "LidarLiteDefn" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LidarLiteDefn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LidarLite\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLidarLiteDefn\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~LidarLiteDefn\fP ()=default"
.br
.ti -1c
.RI "void \fBParseXML\fP (pugi::xml_node lidarLiteNode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file LidarLite\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LidarLiteDefn::LidarLiteDefn ()\fC [default]\fP"

.SS "virtual LidarLiteDefn::~LidarLiteDefn ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void LidarLiteDefn::ParseXML (pugi::xml_node lidarLiteNode)"

.PP
Definition at line 32 of file LidarLite\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
