.TH "LidarFactory" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LidarFactory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LidarFactory\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDragonLidar\fP * \fBCreateLidar\fP (\fBDragonLidar::LIDAR_USAGE\fP usage, int inputPin, int triggerPin)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLidarFactory\fP * \fBGetLidarFactory\fP ()"
.br
.ti -1c
.RI "static \fBDragonLidar\fP * \fBGetLidar\fP (\fBDragonLidar::LIDAR_USAGE\fP usage)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file LidarFactory\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDragonLidar\fP * LidarFactory::CreateLidar (\fBDragonLidar::LIDAR_USAGE\fP usage, int inputPin, int triggerPin)"

.PP
Definition at line 51 of file LidarFactory\&.cpp\&.
.SS "\fBDragonLidar\fP * LidarFactory::GetLidar (\fBDragonLidar::LIDAR_USAGE\fP usage)\fC [static]\fP"

.PP
Definition at line 24 of file LidarFactory\&.cpp\&.
.SS "\fBLidarFactory\fP * LidarFactory::GetLidarFactory ()\fC [static]\fP"

.PP
Definition at line 14 of file LidarFactory\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
