.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlhw/LidarLite.h" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlhw/LidarLite.h
.SH SYNOPSIS
.br
.PP
\fC#include <pugixml/pugixml\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLidarLiteDefn\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSRC_MAIN_CPP_LIDARLITE_H_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SRC_MAIN_CPP_LIDARLITE_H_"

.PP
Definition at line 6 of file LidarLite\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
