.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/controllers/axis/LinearProfile.cpp" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/controllers/axis/LinearProfile.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <controllers/axis/IProfile\&.h>\fP
.br
\fC#include <controllers/axis/LinearProfile\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
