.TH "md__c_1__git_kraken_repos__template_repository_src_main_cpp_xmlhw__r_e_a_d_m_e" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1__git_kraken_repos__template_repository_src_main_cpp_xmlhw__r_e_a_d_m_e \- README 

.PP
 
.SH "Team 302 FIRST robot"
.PP
.SS "Robot Definition"
.PP
.PP
These files will parse the Robot\&.xml file that usese Robot\&.dtd as its definition\&. This defines the mechanisms that are on the robot, which hardware is used, etc\&. So, for instance, the same code can run on the practice robot and the competition robot\&. This file will control which mechanisms are available, motor inversions, what CAD ID or I/O slot the hardware is plugged into, etc\&.
.PP
The only requirement is that the code itself follows good coding practices and checks for a nullptr before using it (e\&.g\&. we would get an error if there wasn't any intake mechanism, but the code blindly assumed that when they asked for the intake mechanism that it wasn't a nullptr)\&. 
