.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlhw/MechanismDefn.cpp" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlhw/MechanismDefn.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <frc/AnalogInput\&.h>\fP
.br
\fC#include <frc/SmartDashboard/SmartDashboard\&.h>\fP
.br
\fC#include <subsys/MechanismFactory\&.h>\fP
.br
\fC#include <subsys/IMechanism\&.h>\fP
.br
\fC#include <xmlhw/AnalogInputDefn\&.h>\fP
.br
\fC#include <xmlhw/DigitalInputDefn\&.h>\fP
.br
\fC#include <xmlhw/MotorDefn\&.h>\fP
.br
\fC#include <xmlhw/ServoDefn\&.h>\fP
.br
\fC#include <utils/Logger\&.h>\fP
.br
\fC#include <xmlhw/MechanismDefn\&.h>\fP
.br
\fC#include <pugixml/pugixml\&.hpp>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
