.TH "MechanismDataDefn" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MechanismDataDefn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MechanismDataDefn\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBmechParamData\fP \fBParseXML\fP (pugi::xml_node MechanismDataNode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file MechanismDataDefn\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBmechParamData\fP MechanismDataDefn::ParseXML (pugi::xml_node MechanismDataNode)\fC [static]\fP"

.PP
Definition at line 50 of file MechanismDataDefn\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
