.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/subsys/MechParamData.h" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/subsys/MechParamData.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <utility>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::pair< \fBIMechanism::MECHANISM_PARAM_TYPE\fP, double > \fBmechParamData\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBmechParamData\fP > \fBmechParameters\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::pair<\fBIMechanism::MECHANISM_PARAM_TYPE\fP, double> \fBmechParamData\fP"

.PP
Definition at line 6 of file MechParamData\&.h\&.
.SS "typedef std::vector<\fBmechParamData\fP> \fBmechParameters\fP"

.PP
Definition at line 7 of file MechParamData\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
