.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlhw/MotorDefn.cpp" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlhw/MotorDefn.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <string>\fP
.br
\fC#include <hw/DragonTalon\&.h>\fP
.br
\fC#include <hw/DragonSparkMax\&.h>\fP
.br
\fC#include <hw/DragonMotorControllerFactory\&.h>\fP
.br
\fC#include <utils/HardwareIDValidation\&.h>\fP
.br
\fC#include <utils/Logger\&.h>\fP
.br
\fC#include <pugixml/pugixml\&.hpp>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
