.TH "PDPDefn" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PDPDefn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PDPDefn\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPDPDefn\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~PDPDefn\fP ()=default"
.br
.ti -1c
.RI "PowerDistributionPanel * \fBParseXML\fP (pugi::xml_node PDPNode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file PDPDefn\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PDPDefn::PDPDefn ()\fC [default]\fP"

.SS "virtual PDPDefn::~PDPDefn ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "PowerDistributionPanel * PDPDefn::ParseXML (pugi::xml_node PDPNode)"

.PP
Definition at line 49 of file PDPDefn\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
