.TH "PIDDefn" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PIDDefn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PIDDefn\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPIDData\fP * \fBParseXML\fP (pugi::xml_node PIDNode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file PIDDefn\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPIDData\fP * PIDDefn::ParseXML (pugi::xml_node PIDNode)\fC [static]\fP"

.PP
Definition at line 49 of file PIDDefn\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
