.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlcontrol/PIDDefn.h" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlcontrol/PIDDefn.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <xmlcontrol/ControlData\&.h>\fP
.br
\fC#include <pugixml/pugixml\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPIDDefn\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
