.TH "PigeonDefn" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PigeonDefn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PigeonDefn\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPigeonDefn\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~PigeonDefn\fP ()=default"
.br
.ti -1c
.RI "void \fBParseXML\fP (pugi::xml_node pigeonNode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file PigeonDefn\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PigeonDefn::PigeonDefn ()\fC [default]\fP"

.SS "virtual PigeonDefn::~PigeonDefn ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void PigeonDefn::ParseXML (pugi::xml_node pigeonNode)"

.PP
Definition at line 46 of file PigeonDefn\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
