.TH "C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlhw/RobotDefn.cpp" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/GitKrakenRepos/TemplateRepository/src/main/cpp/xmlhw/RobotDefn.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <xmlhw/CameraDefn\&.h>\fP
.br
\fC#include <xmlhw/ChassisDefn\&.h>\fP
.br
\fC#include <xmlhw/RobotDefn\&.h>\fP
.br
\fC#include <xmlhw/LidarDefn\&.h>\fP
.br
\fC#include <xmlhw/MechanismDefn\&.h>\fP
.br
\fC#include <xmlhw/LEDDefn\&.h>\fP
.br
\fC#include <xmlhw/PDPDefn\&.h>\fP
.br
\fC#include <xmlhw/PigeonDefn\&.h>\fP
.br
\fC#include <utils/Logger\&.h>\fP
.br
\fC#include <pugixml/pugixml\&.hpp>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
