.TH "SquaredProfile" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SquaredProfile \- Class: \fBCubedProfile\fP Description: This provides profile to be applied to input values\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SquaredProfile\&.h>\fP
.PP
Inherits \fBIProfile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBApplyProfile\fP (double inputVal) const override"
.br
.RI "Method: ApplyProfile Description: Apply the profile "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSquaredProfile\fP * \fBGetInstance\fP ()"
.br
.RI "Method: GetInstance Description: Static singleton method to create the object Returns: SquaredProfile* Singleton squared profile object "
.in -1c
.SH "Detailed Description"
.PP 
Class: \fBCubedProfile\fP Description: This provides profile to be applied to input values\&. 


.PP
Definition at line 37 of file SquaredProfile\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double SquaredProfile::ApplyProfile (double inputVal) const\fC [override]\fP, \fC [virtual]\fP"

.PP
Method: ApplyProfile Description: Apply the profile 
.PP
Implements \fBIProfile\fP\&.
.PP
Definition at line 55 of file SquaredProfile\&.cpp\&.
.SS "\fBSquaredProfile\fP * SquaredProfile::GetInstance ()\fC [static]\fP"

.PP
Method: GetInstance Description: Static singleton method to create the object Returns: SquaredProfile* Singleton squared profile object 
.PP
Definition at line 37 of file SquaredProfile\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
