.TH "TalonTachDefn" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TalonTachDefn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TalonTach\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTalonTachDefn\fP ()=default"
.br
.ti -1c
.RI "virtual \fB~TalonTachDefn\fP ()=default"
.br
.ti -1c
.RI "\fBDragonTalonTach\fP * \fBParseXML\fP (pugi::xml_node talontachNode)"
.br
.RI "{ "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file TalonTach\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TalonTachDefn::TalonTachDefn ()\fC [default]\fP"

.SS "virtual TalonTachDefn::~TalonTachDefn ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBDragonTalonTach\fP * TalonTachDefn::ParseXML (pugi::xml_node talontachNode)"

.PP
{ 
.PP
Definition at line 46 of file TalonTach\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
