.TH "ToggleButton" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ToggleButton \- Class: \fBButtonDecorator\fP Description: This is a decorator for modifying button behavior\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ToggleButton\&.h>\fP
.PP
Inherits \fBButtonDecorator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToggleButton\fP (\fBIButton\fP *button)"
.br
.ti -1c
.RI "\fBToggleButton\fP ()=delete"
.br
.ti -1c
.RI "\fB~ToggleButton\fP ()=default"
.br
.ti -1c
.RI "bool \fBIsButtonPressed\fP () const override"
.br
.RI "Method: IsButtonPressed Description: Read the button and return true if it is pressed and false if it isn't\&. "
.ti -1c
.RI "bool \fBWasButtonReleased\fP () const override"
.br
.RI "Method: WasButtonReleased Description: Read whether the button was released since the last query\&. This is only valid for digital buttons (normal buttons and bumpers)\&. "
.ti -1c
.RI "bool \fBWasButtonPressed\fP () const override"
.br
.RI "Method: WasButtonPressed Description: Read whether the button was pressed since the last query\&. This is only valid for digital buttons (normal buttons and bumpers)\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class: \fBButtonDecorator\fP Description: This is a decorator for modifying button behavior\&. 


.PP
Definition at line 29 of file ToggleButton\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ToggleButton::ToggleButton (\fBIButton\fP * button)"

.PP
Definition at line 22 of file ToggleButton\&.cpp\&.
.SS "ToggleButton::ToggleButton ()\fC [delete]\fP"

.SS "ToggleButton::~ToggleButton ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ToggleButton::IsButtonPressed () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Method: IsButtonPressed Description: Read the button and return true if it is pressed and false if it isn't\&. 
.PP
Reimplemented from \fBButtonDecorator\fP\&.
.PP
Definition at line 29 of file ToggleButton\&.cpp\&.
.SS "bool ToggleButton::WasButtonPressed () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Method: WasButtonPressed Description: Read whether the button was pressed since the last query\&. This is only valid for digital buttons (normal buttons and bumpers)\&. 
.PP
Reimplemented from \fBButtonDecorator\fP\&.
.PP
Definition at line 58 of file ToggleButton\&.cpp\&.
.SS "bool ToggleButton::WasButtonReleased () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Method: WasButtonReleased Description: Read whether the button was released since the last query\&. This is only valid for digital buttons (normal buttons and bumpers)\&. 
.PP
Reimplemented from \fBButtonDecorator\fP\&.
.PP
Definition at line 53 of file ToggleButton\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
