.TH "UltrasonicFactory" 3 "Thu Oct 31 2019" "2020 Template Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UltrasonicFactory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UltrasonicFactory\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDragonUltrasonic\fP * \fBGetDragonUltrasonic\fP (\fBDragonUltrasonic::ULTRASONIC_USAGE\fP usage)"
.br
.ti -1c
.RI "\fBDragonUltrasonic\fP * \fBCreateUltrasonic\fP (\fBDragonUltrasonic::ULTRASONIC_USAGE\fP usage, int analogInChannel)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBUltrasonicFactory\fP * \fBGetUltrasonicFactory\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file UltrasonicFactory\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDragonUltrasonic\fP * UltrasonicFactory::CreateUltrasonic (\fBDragonUltrasonic::ULTRASONIC_USAGE\fP usage, int analogInChannel)"

.PP
Definition at line 52 of file UltrasonicFactory\&.cpp\&.
.SS "\fBDragonUltrasonic\fP * UltrasonicFactory::GetDragonUltrasonic (\fBDragonUltrasonic::ULTRASONIC_USAGE\fP usage)"

.PP
Definition at line 24 of file UltrasonicFactory\&.cpp\&.
.SS "\fBUltrasonicFactory\fP * UltrasonicFactory::GetUltrasonicFactory ()\fC [static]\fP"

.PP
Definition at line 14 of file UltrasonicFactory\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 2020 Template Project from the source code\&.
